steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 10.0'
    inputs:
      version: '10.0.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: 'restore'
      projects: '$(solution)'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: 'build'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  - task: DotNetCoreCLI@2
    displayName: 'Test'
    inputs:
      command: 'test'
      projects: 'test/**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage"'

  - task: PublishCodeCoverageResults@2
    displayName: 'Publish Code Coverage'
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  # ReSharper Code Inspection
  - task: PowerShell@2
    displayName: 'Install JetBrains CLI'
    inputs:
      targetType: 'inline'
      script: |
        dotnet tool install -g JetBrains.ReSharper.GlobalTools

  - task: PowerShell@2
    displayName: 'Run Code Inspection'
    inputs:
      targetType: 'inline'
      script: |
        jb inspectcode Cred-Bench.sln -o=inspectcode-results.sarif --format=Sarif
    continueOnError: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Inspection Results'
    inputs:
      pathToPublish: 'inspectcode-results.sarif'
      artifactName: 'CodeAnalysis'
    condition: always()
